### ISSUE TITLE
Setting debug mode to "True" in Flask make the jobs run twice.

### ISSUE THREAD

**Issue by ANDRESROMEROH** [viniciuschiele/flask-apscheduler#139]
When setting up an app to run in debug mode as the snippet added below, flask-apscheduler will run each job scheduled with _**@scheduler.task('cron', ...)**_ twice.

```python
app.run(host='0.0.0.0', port=5000, debug=True)
```

To replicate add the following Job:
```python
app = Flask(__name__)

scheduler = APScheduler()
scheduler.api_enabled = True
scheduler.init_app(app)
scheduler.start()

@scheduler.task('cron', id='do_job_for_testing', minute='25')
def job_for_testing():
    print('This statement will be printed twice')
```
Which will create the following output:
```shell
$ python app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 235-483-671
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
This statement will be printed twice
This statement will be printed twice
```

**Comment by mattl1598** [comment]
wait that's why all my functions are running twice?! I've been trying to write if statements to catch duplicate jobs but they run so quickly after the first one that I couldn't filter them out.

does removing `debug=True` fix it?

**Comment by viniciuschiele** [comment]
That happens because Flask in debug mode spawns a child process so that it can restart that process each time your code changes, the new child process initializes and start a new `APScheduler`, that's why your jobs are running twice. 

Context: https://stackoverflow.com/questions/25504149/why-does-running-the-flask-dev-server-run-itself-twice

I guess I can detect if the current process is the child one and then I wouldn't allow `APScheduler` to start.

For now, to work around that, you can either to set Flask reloader `use_reloader=False` or `debug=False`.

**Comment by ANDRESROMEROH** [comment]
Thanks @viniciuschiele the use_reloader works fine when running the app locally.
I also ran into the same when deploying the app to Heroku, even though I was setting `use_reloader=False`.

As I was using gunicorn to start the app and I found gunicorn also spawns a child process, so to avoid this from happen I just had to modify my Procfile and add:

`web: gunicorn app:app --preload`

I thought this could be useful for anyone deploying to a Cloud Platform using a WSGI like gunicorn with Flask.
