### ISSUE TITLE
How do I get status information for a task?

### ISSUE THREAD

**Issue by Simon-200** [viniciuschiele/flask-apscheduler#142]
How do I get status information for a task

**Comment by christopherpickering** [comment]
If you are using the API, you can do a get request to `/scheduler/jobs/<job_id>` to get a json of job details.

Otherwise, in your py code, `scheduler.get_job(<job_id>)` will return details as well. Look at the [apscheduler docs](https://apscheduler.readthedocs.io/en/stable/modules/job.html?highlight=job) to see what is available.
Once a task is started by the scheduler, the scheduler will have no further information... except next run if you have a scheduler set up.
