### ISSUE TITLE
flask-context

### ISSUE THREAD

**Issue by shitone** [viniciuschiele/flask-apscheduler#45]
Hi, @viniciuschiele :
I read the example `flask_context.py`. I have some questions about that. 
1. Is the the `app` stored in the database? And then we get the `app` from database through `db.app`?
2. If I don't wanna use database, how could I get the app context in the thread?
Thank you!

**Comment by viniciuschiele** [comment]
Hi @shitone 

The `app` variable is the Flask app and it is not stored in database, I just set `db.app = app` because `app` is not a global variable and I needed to access it within my task.

```db``` is a global variable so that within the task you can get the ```db``` object to access the database.

The `app` variable could also be a global variable, in such case you wouldn't need to set `db.app = app`

I don't know if I was clear, let know if you have more questions.

**Comment by shitone** [comment]
Got it! I'll have an try in my project. Thks.
