### ISSUE TITLE
examples/jobs.py behavoir

### ISSUE THREAD

**Issue by zingdle** [viniciuschiele/flask-apscheduler#69]
I run the code in `examples/jobs.py` but got 
```
1 2
1 2
```
 every 10 second. Is that a expected behavior?

Also, I found that the first `1 2` appears after 10 second. Is there's a way to execute the job instantly?

I'm using `Flask 0.12.2` and `Flask-APScheduler 1.8.0`.

**Comment by viniciuschiele** [comment]
That probably happens because Flask is running in debug mode.

You can try running Flask like this: 
```python
app.run(use_reloader=False)
```
For more info:
https://stackoverflow.com/questions/14874782/apscheduler-in-flask-executes-twice

I'm not aware of any way to run a job immediately, but you can have a look at [APScheduler's documentation](http://apscheduler.readthedocs.io/en/latest/userguide.html), maybe there is an option for that. Let me know if you find it.

**Comment by waro163** [comment]
I also want to execute my job instantly rather than after one period, now do you have any way to solve it?

**Comment by zingdle** [comment]
@waro163 Sorry, I didn't. You may share your solution once you figure it out :-)
