### ISSUE TITLE
RuntimeError: Working outside of application context. 

### ISSUE THREAD

**Issue by ljq132008** [viniciuschiele/flask-apscheduler#76]
flask-apscheduler config like this:
SCHEDULER_JOBSTORES = {
        'default': SQLAlchemyJobStore(url='mysql+pymysql://xxx:xxxx@192.168.1.101/xxx')
    }
    SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 20}
    }
    SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 3
    }
    SCHEDULER_API_ENABLED = True

when I restart the application, jobs dosen't work:
RuntimeError: Working outside of application context.

job code:
scheduler = current_app.apscheduler

def job1(a, b):

    with scheduler.app.app_context():
        print('job1 running...')
        change_log = SchedulerJobsChangeLog('job1', 'job1 running')
        db.session.add(change_log)
        db.session.commit()

**Comment by viniciuschiele** [comment]
Can you have a look at this [example](https://github.com/viniciuschiele/flask-apscheduler/blob/master/examples/flask_context.py) to see if there is something different from your own code?
Or if you could provide a [gist](https://gist.github.com/) with a full example so that I can try to figure it out.
Thanks

**Comment by viniciuschiele** [comment]
I have found out you can't use **current_app** within a task, not sure if that is your case though.
